
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]
    env:
      PYTHONPATH: src

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build & dev tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry config virtualenvs.create true
          poetry install --with dev --no-interaction

      - name: Lint (ruff)
        continue-on-error: true
        run: |
          # Run ruff linter but allow the job to continue on failure so the
          # workflow can complete. Lint failures will still show in the logs.
          poetry run ruff check . || true

      - name: Type check (mypy)
        run: |
          poetry run mypy src --ignore-missing-imports --pretty

      - name: Run tests
        run: |
          # Run tests from repository root; PYTHONPATH is set at job level
          poetry run pytest -q

      - name: Build distributions
        run: |
          poetry run python -m build --sdist --wheel

      - name: Validate distributions (twine check)
        run: |
          poetry run python -m pip install twine
          poetry run python -m twine check dist/*


