name: Test Coverage

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  coverage:
    name: Run tests & upload coverage
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: src

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install Poetry and dependencies
        run: |
          pip install poetry
          poetry env use 3.11
          poetry config virtualenvs.create true
          poetry install --with dev --no-interaction

      - name: Run tests with coverage
        run: |
          poetry run pytest --cov=src/liftlens --cov-report=xml --cov-report=term-missing -v

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
          flags: unittests
          verbose: true
